package com.ennea.enneaservices.enums;

import lombok.Getter;

@Getter
public enum ErrorEnum {
    FORBIDDEN("Access Denied", "ERR101"),
    USER_SESSION_EXPIRED("Session expired, sign in again", "ERR102"),
    REQUIRED_DRUG_LICENSE("Drug licence copy is required", "ERR103"),
    USER_REGISTRATION_FAILED("User registration failed", "ERR104"),
    INVALID_USER_STATUS("Invalid user status, contact admin", "ERR105"),
    BLOCKED_BY_ADMIN("You have been blocked by the admin", "ERR106"),
    USER_SESSION_CREATION_FAILED("Unable to create user session while logining", "ERR107"),
    UNABLE_TO_FIND_ROLES("Unable to find the roles", "ERR108"),
    UNABLE_TO_GET_USERS("Unable to find the users", "ERR109"),
    UNABLE_TO_FIND_USER("Unable to find the user", "ERR110"),
    UNABLE_TO_GENERATE_OTP("Unable to generate OTP, please retry.", "ERR111"),
    UNABLE_TO_FIND_PASSWORD_RESET_REQUEST("Unable to find the password reset request", "ERR112"),
    UNABLE_TO_VERIFY_OTP("Unable to verify OTP, please retry.", "ERR113"),
    GENERIC("Access Denied", "ERR100"),
    FORBIDDEN_ORDER_FETCH("Forbidden from fetching order(s)", "ERR114"),
    NOT_A_VALID_ORDER("Not a valid order", "ERR115"),
    SUPPLIER_DOES_NOT_EXIST("Supplier does not exist", "ERR116"),
    UNABLE_TO_UPDATE_CART("Unable to update cart", "ERR117"),
    UNABLE_TO_CLEAR_CART("Unable to clear cart", "ERR118"),
    ASSOCIATION_DOES_NOT_EXIST("Association does not exist", "ERR119"),
    UNAUTHORIZED_PAYMENT("Not authorized to make payment", "ERR120"),
    UNABLE_TO_FIND_CART("Unable to find the cart", "ERR121"),
    FORBIDDEN_REORDER("Forbidden from re-ordering", "ERR122"),
    UNAUTHORIZED_MODE_SWITCH("Not authorized to switch mode", "ERR123"),
    FORBIDDEN_CUSTOMER_FETCH("Forbidden from fetching customers", "ERR124"),
    UNABLE_TO_FIND_PRODUCT("Unable to find product", "ERR125"),
    CANNOT_CREATE_EMPTY_GROUP("Cannot create empty group", "ERR126"),
    UNABLE_TO_FIND_USER_GROUP("Unable to find user group", "ERR127"),
    UNABLE_TO_FIND_ASSOCIATION_OR_STATUS("Unable to find association or status", "ERR128"),
    DUPLICATE_USERNAME("Duplicate username", "ERR129"),
    DUPLICATE_PHONE_NUMBER("Duplicate phone number", "ERR130"),
    DUPLICATE_DRUG_LICENSE_NUMBER("Duplicate drug license number", "ERR131"),
    ILLEGAL_USER_STATUS_UPADTE("Illegal user status update", "ERR132"),
    UNABLE_TO_CREATE_COUPONS("Unable to create coupons", "ERR133"),
    UNABLE_TO_FIND_COUPON_RULE("Unable to find coupon rule", "ERR134"),
    UNABLE_TO_FIND_COUPON_CASES("Unable to find coupon cases", "ERR135"),
    INVALID_COUPON_CASES("Invalid coupon cases", "ERR136"),
    CANNOT_UPDATE_COUPON_RULE("Cannot update existing coupon rule", "ERR137"),
    CANNOT_UPDATE_COUPON_CASE("Cannot update existing coupon case", "ERR138"),
    FORBIDDEN_INVOICE_FETCH("Unable to fetch invoice details", "ERR139"),
    NOT_A_VALID_INVOICE("Not a valid invoice", "ERR140"),
    INVALID_END_DATE_FOR_OFFER_CREATION("Invalid end date for offer creation", "ERR141"),
    UNABLE_TO_FIND_OFFER("Unable to find offer", "ERR142"),
    UNABLE_TO_FIND_COUPON("Unable to find coupon", "ERR143"),
    FORBIDDEN_PRODUCT_SEARCH("Forbidden from searching products", "ERR144"),
    SUPPLIER_ASSOCIATION_DOES_NOT_EXIST("Supplier association does not exist", "ERR145"),
    UNABLE_TO_FIND_REPRESENTATIVE_ASSOCIATION("Unable to find representative association", "ERR146"),
    UNABLE_TO_FIND_REQUEST_STATUS("Unable to find request status", "ERR147"),
    INVALID_REQUEST_STATUS_CHANGE("Invalid request status change", "ERR148"),
    BAD_CREDENTIALS("Bad credentials, please try again", "ERR149"),
    INVALID_ROLE_UPDATE("Invalid role update", "ERR150"),
    USER_CREATION_FAILED("User creation failed", "ERR151"),
    UNABLE_TO_FIND_CUSTOMER_ASSOCIATION("Unable to find customer association", "ERR152"),
    DUPLICATE_PARTY_CODE("Party code already exists", "ERR153"),
    FORBIDDEN_SUPPLIER_SEARCH("Forbidden from searching suppliers", "ERR154"),
    FORBIDDEN_ORDER_UPDATE("Forbidden from updating order details", "ERR155"),
    FORBIDDEN_SUPPLIER_CUSTOMER_SEARCH("Forbidden from fetching supplier customer associations", "ERR159"),
    FORBIDDEN_CART_FETCH("Forbidden from fetching cart", "ERR160"),
    UNABLE_TO_FIND_ORDER_TYPE("Unable to find order type", "ERR161"),
    UNABLE_TO_PARSE_JSON("Unable to parse json", "ERR162"),
    USER_DOES_NOT_EXIST("User does not exist", "ERR163"),
    USER_NOT_APPROVED("User not approved", "ERR164"),
    FORBIDDEN_SUPPLIER_REPRESENTATIVE_FETCH("Unable to fetch supplier representative associations", "ERR165"),
    EMPTY_CUSTOMER_LIST("Empty customer list", "ERR166"),
    INVALID_INVOICING_SETTINGS("Invalid invoicing settings", "ERR167"),
    UNABLE_TO_INVOICE_ORDERS("Unable to invoice orders", "ERR168"),
    CANNOT_CREATE_HETERO_GROUP("Cannot create group with users with multiple roles", "ERR169"),
    TOKEN_DOES_NOT_EXIST("Token does not exist", "ERR170"),
    UNABLE_TO_FIND_BILL("Unable to find bill", "ERR171"),
    FORBIDDEN_TO_DELETE_CUSTOMER("Forbidden from deleting customer", "ERR172"),
    FORBIDDEN_ORDER_CREATE("Forbidden from creating order", "ERR173"),
    UNABLE_TO_UPDATE_ORDER("Unable to update order", "ERR174"),
    UNABLE_TO_CREATE_ORDER("Unable to create order", "ERR175"),
    FORBIDDEN_TO_SEND_PRESCRIPTION_URL("Forbidden to send prescription url", "ERR176"),
    USER_EXISTS_IN_THE_CHAIN("User already exists in the chain", "ERR177"),
    UNABLE_TO_PROCESS_PACT_ORDER("Unable to process pact order", "ERR178"),
    UNABLE_TO_FIND_ERP_CREDENTIALS("Unable to find ERP credentials", "ERR179"),
    PRODUCT_CODE_ALREADY_EXISTS("Product Code already exists", "ERR180"),
    UNABLE_TO_UPDATE_DRUG_LICENSE("Unable to update drugLicense", "ERR181"),
    FILE_TYPE_NOT_SUPPORTED("Unable to process file type", "ERR182"),
    FAILED_TO_PROCESS_FILE("Unable to process file", "ERR183"),
    UNABLE_TO_FIND_LEDGER("Unable to find ledger", "ERR184"),
    INVALID_SUPPLIER_CUSTOMER_UPDATE("Invalid party name or party code", "ERR185"),
    SUPPLIER_PAYMENTS_NOT_ENABLED("Payments not enabled, reach out to support.", "ERR187"),
    UNABLE_TO_CREATE_PAYMENT_REQUEST("Unable to create payment request", "ERR188"),
    CHECKSUM_VALIDATION_FAILED("Checksum validation failed", "ERR189"),
    UNABLE_TO_GENERATE_TOKEN("Unable to generate token", "ERR190"),
    UNABLE_TO_FIND_PAYMENT_GATEWAY("Unable to find payment gateway", "ERR191"),
    UNABLE_TO_PARSE_RESPONSE("Unable to parse response", "ERR192"),
    UNABLE_TO_FIND_PAYMENT_REQUEST("Unable to find payment request", "ERR193"),
    DISBURSAL_DEPENDENCY_FAILURE("Disbursal dependency failure", "ERR194"),
    UNABLE_TO_ENCRYPT_REQUEST("Unable to encrypt request", "ERR195"),
    UNABLE_TO_DECRYPT_RESPONSE("Unable to encrypt response", "ERR196"),
    UNABLE_TO_SERIALIZE_REQUEST("Unable to serialize request", "ERR197"),
    UNABLE_TO_DESERIALIZE_RESPONSE("Unable to deserialize response", "ERR198"),
    UNABLE_TO_FIND_PENDING_DISBURSALS("Unable to find pending disbursals", "ERR199"),
    CUSTOMER_PAYMENTS_NOT_ENABLED("Payments not enabled, reach out to supplier.", "ERR200"),
    DUPLICATE_PAYMENT_URL_GENERATION("Payment is already being processed", "ERR201"),
    UNABLE_TO_GENERATE_CHECKSUM("Unable to generate checksum", "ERR202"),
    UNABLE_TO_FIND_PAYMENT_TYPE("Unable to find payment type", "ERR203"),
    UNABLE_TO_DELETE_OFFER("Unable to delete the offer", "ERR204"),

    UNABLE_TO_UPLOAD_REPORT("Unable to upload report", "ERR205"),
    UNABLE_TO_FIND_SUBSCRIPTION("Unable to find subscription", "ERR206"),
    UNABLE_TO_FIND_DISBURSAL_STATUS("Unable to find the disbursal status", "ERR207"),
    UNABLE_TO_GENERATE_INGESTION_TEMPLATE("Unable to generate outstanding ingestion template", "ERR208"),
    UNABLE_PERFORM_OUTSTANDING_AMOUNT_INGESTION("Unable perform outstanding amount ingestion", "ERR209"),
    UNABLE_TO_UPLOAD_INVENTORY("Unable to upload inventory", "ERR210"),
    UNABLE_TO_PARSE_PO("Unable to parse purchase order sheet", "ERR211"),
    UNABLE_TO_FIND_QUOTATION("Unable to find quotation", "ERR212"),

    UNABLE_TO_CREATE_QUOTATION_ORDER("Unable to create quotation order", "ERR213"),

    UNABLE_TO_UPDATE_QUOTATION_ORDER("Unable to update quotation order", "ERR214"),
    UNABLE_TO_FIND_TEMPLATE("Unable to find template for user", "ERR215"),
    INVENTORY_ASSOCIATION_DOES_NOT_EXIST("Inventory Association does not exist", "ERR216"),
    INVALID_INVENTORY_ITEM("Invalid Inventory Item", "ERR217"),
    INVALID_EDIT_SETTING_SELECTION("Invalid Setting selected for Edit", "ERR218"),
    ORDER_PLACEMENT_FAILED("No orders placed", "ERR219"),
    INVALID_PROMOTION_TEMPLATE_SELECTION("Invalid choice of Promotion Template", "ERR220"),
    UNABLE_TO_FIND_PROFILE_UPDATE_REQUEST("Unable to find profile update request", "ERR221"),
    PROFILE_UPDATE_REQUEST_FAILED("Unable to update user profile", "ERR222"),
    UNABLE_TO_UPLOAD_TO_S3("Unable to upload to S3", "ERR223"),
    INVALID_FILE_TYPE_FOR_BROADCAST("Invalid File type for selected Broadcast template", "ERR224"),
    UNABLE_TO_FIND_BROADCAST_ATTACHMENT("Unable to find broadcast attachment", "ERR225"),
    INSUFFICIENT_SEND_BALANCE("Insufficient sends for the uploaded file", "ERR226"),
    NO_PARSER_CONFIG_FOUND("No Parser Config found", "ERR227"),
    UNABLE_TO_CONVERT_PARSER_CONFIG_STR_TO_JSON("Unable to convert Parser config string to JSON", "ERR228"),
    UNABLE_TO_CONVERT_PARSER_CONFIG_JSON_TO_STR("Unable to convert Parser config JSON to string", "ERR229"),
    UNABLE_TO_CONVERT_PARSER_CONFIG_JSON_TO_OBJ("Unable to convert Parser config JSON to Object", "ERR230"),
    MUTHOOTH_API_CALL_FAILED("Error while fetching credit details", "ERR231"),
    UNABLE_TO_FIND_DETAILS("Unable to find the required details", "ERR232"),
    EMPTY_ORDER_LIST("Empty order list", "ERR233"),
    UNABLE_TO_UPDATE_PRODUCT("Unable to update product", "ERR234"),
    UNABLE_TO_FIND_BENEFICIARY_DETAILS("Unable to find beneficiary details", "ERR131"),
    ASSOCIATION_ALREADY_EXISTS("Association already exists", "ERR132"),
    UNABLE_TO_CREATE_ASSOCIATION("Unable to create supplier customer association", "ERR133"),
    UNABLE_TO_FIND_PRODUCT_SHORTAGE("Unable to find product shortage", "ERR235"),
    UNABLE_TO_UPLOAD_LEDGER("Unable to upload ledger", "ERR234"),
    UNABLE_TO_UPLOAD_SHORTAGE_PRODUCTS("Unable to upload shortage products", "ERR236"),
    PRODUCT_SHORTAGE_ALREADY_EXISTS("Product shortage already exists", "ERR237"),
    NO_TEXT_FOUND("No text found. Please try uploading a clear image", "ERR238"),
    UNABLE_TO_EXTRACT_TEXT("Unable to extract text, Please try again later", "ERR239"),
    UNABLE_TO_UPLOAD_SHORTAGE_IMAGE("Unable to upload shortage image", "ERR240"),
    USER_SESSION_UNKNOWN("Unable to find User Session", "ERR241"),
    SMS_DEPENDENCY_FAILURE("SMS dependency failure, please try again later", "ERR242"),
    UNABLE_TO_UPLOAD_PROFILE_IMAGE("Unable to upload profile image", "ERR243"),
    UNABLE_TO_DELETE_PROFILE_IMAGE("Unable to delete profile image", "ERR244"),
    PDFBOX_WRITE_FAILURE("Unable to generate PDF, please try again later", "ERR245"),
    INVALID_USER_DETAILS("Enter valid user details", "ERR246");

    private final String message;
    private final String code;

    ErrorEnum(String message, String code) {
        this.message = message;
        this.code = code;
    }

}


